DROP SCHEMA EST_IV;
CREATE SCHEMA EST_IV;

USE EST_IV;

-- Tabela de Alunos
CREATE TABLE IF NOT EXISTS ALUNOS (
COD_ALUNO INT PRIMARY KEY,
NOME VARCHAR(100) NOT NULL,
CPF INT,
DATA_NASCIMENTO DATE NOT NULL,
INT_MODALIDADE TEXT,
TELEFONE_ALN VARCHAR(15),
CIDADE_ALN VARCHAR(50),
ESTADO_ALN VARCHAR(50),
PAIS_ALN VARCHAR(50),
NUMRUA_ALN VARCHAR(10),
BAIRRO_ALN VARCHAR(50)
);

-- Tabela de Instrutores
CREATE TABLE IF NOT EXISTS INSTRUTORES (
COD_INSTRUTOR INT PRIMARY KEY,
NOME VARCHAR(100) NOT NULL,
CPF INT,
TELEFONE VARCHAR(15),
ESPECIALIZACAO VARCHAR(100)
);

-- Tabela de Modalidades
CREATE TABLE IF NOT EXISTS MODALIDADES (
COD_MODALIDADE INT PRIMARY KEY,
NOME VARCHAR(100) NOT NULL,
DESCRICAO TEXT,
CAPACIDADE INT NOT NULL
);

-- Tabela de Planos de Treinamento
CREATE TABLE IF NOT EXISTS PLANOS_TREINAMENTO (
COD_PLANO INT PRIMARY KEY,
ID_ALUNO INT NOT NULL,
ID_INSTRUTOR INT NOT NULL,
DESCRICAO TEXT,
DATA_CRIACAO DATE NOT NULL,
CONSTRAINT FK_PLAN_ALUNOS FOREIGN KEY (ID_ALUNO) REFERENCES ALUNOS(COD_ALUNO),
CONSTRAINT FK_PLAN_INSTRUTOR FOREIGN KEY (ID_INSTRUTOR) REFERENCES INSTRUTORES(COD_INSTRUTOR)
);

-- Tabela de Aulas
CREATE TABLE IF NOT EXISTS AULAS (
COD_AULA INT PRIMARY KEY,
ID_MODALIDADE INT NOT NULL,
DATA_AULA DATE NOT NULL,
HORARIO TIME NOT NULL,
INSTRUTOR_ID INT NOT NULL,
CONSTRAINT FK_AUL_MODALIDADES FOREIGN KEY (ID_MODALIDADE) REFERENCES MODALIDADES(COD_MODALIDADE),
CONSTRAINT FK_AUL_INSTRUTOR FOREIGN KEY (INSTRUTOR_ID) REFERENCES INSTRUTORES(COD_INSTRUTOR)
);

-- Tabela de Matrículas
CREATE TABLE IF NOT EXISTS MATRICULAS (
COD_MATRICULA INT PRIMARY KEY,
ID_ALUNO INT NOT NULL,
ID_MODALIDADE INT NOT NULL,
DATA_MATRICULA DATE NOT NULL,
STATUS VARCHAR(20) NOT NULL,
CONSTRAINT FK_MATRICULA_ALUNO FOREIGN KEY (ID_ALUNO) REFERENCES ALUNOS(COD_ALUNO),
CONSTRAINT FK_MATRICULA_MODALIDADE FOREIGN KEY (ID_MODALIDADE) REFERENCES MODALIDADES(COD_MODALIDADE)
);

-- Tabela de Pagamentos
CREATE TABLE IF NOT EXISTS PAGAMENTOS (
COD_PAGAMENTO INT PRIMARY KEY,
ID_MATRICULA INT NOT NULL,
VALOR DECIMAL(10, 2) NOT NULL,
DATA_PAGAMENTO DATE NOT NULL,
STATUS_PAGAMENTO VARCHAR(20) NOT NULL,
CONSTRAINT FK_PAGAMENTO_MATRICULA FOREIGN KEY (ID_MATRICULA) REFERENCES MATRICULAS(COD_MATRICULA)
);

-- Adicionando as chaves estrangeiras para a tabela PLANOS_TREINAMENTO
ALTER TABLE PLANOS_TREINAMENTO 
ADD CONSTRAINT FK_PLAN_ALUNOS FOREIGN KEY (ID_ALUNO) REFERENCES ALUNOS(COD_ALUNO);

ALTER TABLE PLANOS_TREINAMENTO 
ADD CONSTRAINT FK_PLAN_INSTRUTOR FOREIGN KEY (ID_INSTRUTOR) REFERENCES INSTRUTORES(COD_INSTRUTOR);

-- Adicionando as chaves estrangeiras para a tabela AULAS
ALTER TABLE AULAS 
ADD CONSTRAINT FK_AUL_MODALIDADE FOREIGN KEY (ID_MODALIDADE) REFERENCES MODALIDADES(COD_MODALIDADE);

ALTER TABLE AULAS 
ADD CONSTRAINT FK_AUL_INSTRUTOR FOREIGN KEY (INSTRUTOR_ID) REFERENCES INSTRUTORES(COD_INSTRUTOR);

-- Adicionando as chaves estrangeiras para a tabela MATRICULAS
ALTER TABLE MATRICULAS 
ADD CONSTRAINT FK_MATRICULA_ALUNO FOREIGN KEY (ID_ALUNO) REFERENCES ALUNOS(COD_ALUNO);

ALTER TABLE MATRICULAS 
ADD CONSTRAINT FK_MATRICULA_MODALIDADE FOREIGN KEY (ID_MODALIDADE) REFERENCES MODALIDADES(COD_MODALIDADE);

-- Adicionando as chaves estrangeiras para a tabela PAGAMENTOS
ALTER TABLE PAGAMENTOS 
ADD CONSTRAINT FK_PAGAMENTO_MATRICULA FOREIGN KEY (ID_MATRICULA) REFERENCES MATRICULAS(COD_MATRICULA);

